name: C++ CI Workflow with conda-forge dependencies

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}@conda]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true

    - name: Dependencies
      shell: bash -l {0}
      run: |
        # Compilation related dependencies
        mamba install bazel compilers make ninja pkg-config which

        # Actual dependencies
        mamba install fmt spdlog gflags eigen python numpy fcl libsdformat10 libignition-math6 tinyxml2 yaml-cpp suitesparse ipopt glib

    - name: Download drake
      shell: bash -l {0}
      run: |
        git clone https://github.com/traversaro/drake
        cd drake
        git checkout conda-fall21

    - name: Test common
      shell: bash -l {0}
      run: |
        cd drake/common
        export BAZEL_CXXOPTS=-std=c++17
        bazel test -s --define=NO_SCS=ON --define=NO_DREAL=ON --define=NO_NLOPT=ON --define=NO_CSDP=ON ...
    
    - name: Test math
      shell: bash -l {0}
      run: |
        cd drake/math
        export BAZEL_CXXOPTS=-std=c++17
        bazel test -s  --define=NO_SCS=ON --define=NO_DREAL=ON --define=NO_NLOPT=ON --define=NO_CSDP=ON ...
    
    - name: Build
      shell: bash -l {0}
      run: |
        cd drake
        export BAZEL_CXXOPTS=-std=c++17
        bazel build -s --define=NO_SCS=ON --define=NO_DREAL=ON --define=NO_NLOPT=ON --define=NO_CSDP=ON //:install

    - name: Install
      shell: bash -l {0}
      run: |
        cd drake
        export BAZEL_CXXOPTS=-std=c++17
        bazel run -s --define=NO_SCS=ON --define=NO_DREAL=ON --define=NO_NLOPT=ON --define=NO_CSDP=ON //:install -- ${GITHUB_WORKSPACE}/install
